# Generated by Django 5.0.7 on 2025-03-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresponse',
            name='audio_response',
            field=models.FileField(blank=True, null=True, upload_to='responses/'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='job_profile',
            field=models.CharField(max_length=255),
        ),
    ]
