# Generated by Django 5.0.7 on 2025-03-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_interviewresponse_audio_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewresponse',
            name='audio_response',
        ),
    ]
