# Generated by Django 5.0.7 on 2025-03-27 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_interviewsession_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewresponse',
            name='created_at',
        ),
        migrations.AddField(
            model_name='interviewresponse',
            name='audio_response',
            field=models.FileField(blank=True, null=True, upload_to='audio_responses/'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
